AWSTemplateFormatVersion: "2010-09-09"
Description: Amazon SageMaker Studio Starter
Mappings:
  SubnetCIDRBlocks:
    VPC:
      CIDR: "10.0.0.0/16"
    Subnet1:
      CIDR: "10.0.0.0/24"
    Subnet2:
      CIDR: "10.0.1.0/24"
    Subnet3:
      CIDR: "10.0.2.0/24"
Resources:
  SMStudioWorkshopVPC:
    Type: AWS::EC2::VPC
    Properties:
      EnableDnsSupport: true
      EnableDnsHostnames: true
      CidrBlock: !FindInMap ["SubnetCIDRBlocks", "VPC", "CIDR"]
      Tags:
        - Key: Name
          Value: SMStudioWorkshopVPC
  Subnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs: { Ref: "AWS::Region" }
      VpcId: !Ref SMStudioWorkshopVPC
      CidrBlock: !FindInMap ["SubnetCIDRBlocks", "Subnet1", "CIDR"]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: Subnet1
  Subnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Fn::Select:
          - 1
          - Fn::GetAZs: { Ref: "AWS::Region" }
      VpcId: !Ref SMStudioWorkshopVPC
      CidrBlock: !FindInMap ["SubnetCIDRBlocks", "Subnet2", "CIDR"]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: Subnet2
  Subnet3:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Fn::Select:
          - 2
          - Fn::GetAZs: { Ref: "AWS::Region" }
      VpcId: !Ref SMStudioWorkshopVPC
      CidrBlock: !FindInMap ["SubnetCIDRBlocks", "Subnet3", "CIDR"]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: Subnet3
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: SMStudioWorkshopIGW
  IGWAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref SMStudioWorkshopVPC
      InternetGatewayId: !Ref InternetGateway
  SMStudioWorkshopRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref SMStudioWorkshopVPC
      Tags:
        - Key: Name
          Value: SMStudioWorkshopRouteTable
  SMStudioWorkshopRoute:
    Type: AWS::EC2::Route
    DependsOn: IGWAttachment
    Properties:
      RouteTableId: !Ref SMStudioWorkshopRouteTable
      DestinationCidrBlock: "0.0.0.0/0"
      GatewayId: !Ref InternetGateway
  Subnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref Subnet1
      RouteTableId: !Ref SMStudioWorkshopRouteTable
  Subnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref Subnet2
      RouteTableId: !Ref SMStudioWorkshopRouteTable
  Subnet3RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref Subnet3
      RouteTableId: !Ref SMStudioWorkshopRouteTable
  SMStudioSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: VPC Security Group
      VpcId: !Ref SMStudioWorkshopVPC
  SMStudioSecurityGroupIngress:
   Type: 'AWS::EC2::SecurityGroupIngress'
   Properties:
      GroupId: !Ref SMStudioSecurityGroup
      IpProtocol: -1
      FromPort: -1
      ToPort: -1
      SourceSecurityGroupId: !GetAtt SMStudioSecurityGroup.GroupId
  SMStudioExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: SMStudioExecutionRole
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [sagemaker.amazonaws.com]
            Action: ["sts:AssumeRole"]
          - Effect: Allow
            Principal:
              Service: [codebuild.amazonaws.com]
            Action: ["sts:AssumeRole"]
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess
      Policies:
        - PolicyName: SMStudioExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"          
            Statement:
              - Effect: Allow
                Action:
                  - "s3:GetObject"
                  - "s3:PutObject"
                  - "s3:DeleteObject"
                  - "s3:ListBucket"
                Resource: "arn:aws:s3:::*"
        - PolicyName: SMStudioCodeBuildPolicy
          PolicyDocument:
            Version: "2012-10-17"          
            Statement:
              - Effect: Allow
                Action:
                  - "codebuild:DeleteProject"
                  - "codebuild:CreateProject"
                  - "codebuild:BatchGetBuilds"
                  - "codebuild:StartBuild"
                Resource: "arn:aws:codebuild:*:*:project/sagemaker-studio*"
              - Effect: Allow
                Action:
                  - "logs:CreateLogStream"
                Resource: "arn:aws:logs:*:*:log-group:/aws/codebuild/sagemaker-studio*"
              - Effect: Allow
                Action:
                  - "logs:GetLogEvents"
                  - "logs:PutLogEvents"
                Resource: "arn:aws:logs:*:*:log-group:/aws/codebuild/sagemaker-studio*:log-stream:*"
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                Resource: "*"
              - Effect: Allow
                Action:
                  - "ecr:CreateRepository"
                  - "ecr:BatchGetImage"
                  - "ecr:CompleteLayerUpload"
                  - "ecr:DescribeImages"
                  - "ecr:DescribeRepositories"
                  - "ecr:UploadLayerPart"
                  - "ecr:ListImages"
                  - "ecr:InitiateLayerUpload"
                  - "ecr:BatchCheckLayerAvailability"
                  - "ecr:PutImage"
                Resource: "arn:aws:ecr:*:*:repository/sagemaker-studio*"
              - Effect: Allow
                Action:
                  - "ecr:GetAuthorizationToken"
                Resource: "*"
              - Effect: Allow
                Action:
                  - "s3:GetObject"
                  - "s3:DeleteObject"
                  - "s3:PutObject"
                Resource: "arn:aws:s3:::sagemaker-*/*"
              - Effect: Allow
                Action:
                  - "s3:CreateBucket"
                Resource: "arn:aws:s3:::sagemaker*"
              - Effect: Allow
                Action:
                  - "iam:GetRole"
                  - "iam:ListRoles"
                Resource: "*"
              - Effect: Allow
                Action:
                  - "iam:PassRole"
                Resource: "arn:aws:iam::*:role/*"
                Condition:
                  StringLikeIfExists:
                    iam:PassedToService: codebuild.amazonaws.com
  SMStudioAdmin: 
    Type: AWS::IAM::User
    Properties: 
      LoginProfile: 
        Password: Workshopuser#123
        PasswordResetRequired: false
      UserName: smstudioadmin
  SMStudioAdminCredentials:
    Type: AWS::IAM::AccessKey
    Properties:
      Status: Active
      UserName: !Ref SMStudioAdmin
  SMStudioAdminRole:
    DependsOn: SMStudioAdmin
    Type: AWS::IAM::Role
    Properties:
      RoleName: SMStudioAdminRole
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [sagemaker.amazonaws.com]
            Action: ["sts:AssumeRole"]
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:user/smstudioadmin'
            Action: ["sts:AssumeRole"]
      Path: /
  SMStudioAdminPolicy:                                                                                                                                                                                                                                                                     
    DependsOn: SMStudioAdminRole
    Type: AWS::IAM::ManagedPolicy
    Properties: 
      PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "sagemaker:CreateDomain"
                  - "sagemaker:GetSagemakerServicecatalogPortfolioStatus"
                Resource: "*"
              - Effect: Allow
                Action:
                  - "sagemaker:CreateUserProfile"
                Resource: "*"
                Condition:
                  ForAnyValue:StringEquals:
                    aws:TagKeys: 'studiouserid'
              - Effect: Allow
                Action:
                  - "iam:CreateServiceLinkedRole"
                Resource: "*"
              - Effect: Allow
                Action:
                  - "servicecatalog:ListAcceptedPortfolioShares"
                Resource: "*"
      ManagedPolicyName: SMStudioAdminPolicy
      Roles: 
        - SMStudioAdminRole
  SMStudioDevPolicy:                                                                                                                                                                                                                                                                     
    DependsOn: SMStudioAdminRole
    Type: AWS::IAM::ManagedPolicy
    Properties: 
      PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "sagemaker:CreateApp"
                Resource: "*"
              - Effect: Allow
                Action:
                  - "sagemaker:InvokeEndpoint"
                Resource: "*"
              - Effect: Allow
                Action:
                  - "sagemaker:AddTags"
                Resource: "*"
              - Effect: Allow
                Action:
                  - "sagemaker:Delete*"
                  - "sagemaker:Stop*"
                  - "sagemaker:Update*"
                  - "sagemaker:Start*"
                  - "sagemaker:DisassociateTrialComponent"
                  - "sagemaker:AssociateTrialComponent"
                  - "sagemaker:BatchPutMetrics"
                  - "sagemaker:*Image*"
                  - "sagemaker:*Endpoint*"
                Resource: "*"
              - Effect: Allow
                Action:
                  - "iam:PassRole"
                Resource: "*"
                Condition:
                  StringEquals:
                    iam:PassedToService: sagemaker.amazonaws.com
      ManagedPolicyName: SMStudioDevPolicy
      Roles: 
        - SMStudioAdminRole
  SMStudioReadOnlyPolicy:                                                                                                                                                                                                                                                                     
    DependsOn: SMStudioAdminRole
    Type: AWS::IAM::ManagedPolicy
    Properties: 
      PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "sagemaker:Describe*"
                  - "sagemaker:GetSearchSuggestions"
                  - "sagemaker:List*"
                  - "sagemaker:*App"
                  - "sagemaker:Search"
                  - "sagemaker:RenderUiTemplate"
                  - "sagemaker:BatchGetMetrics"
                  - "sagemaker:GetSagemakerServicecatalogPortfolioStatus"
                Resource: "*"
              - Effect: Allow
                Action:
                  - "ec2:DescribeDhcpOptions"
                  - "ec2:DescribeNetworkInterfaces"
                  - "ec2:DescribeRouteTables"
                  - "ec2:DescribeSecurityGroups"
                  - "ec2:DescribeSubnets"
                  - "ec2:DescribeVpcEndpoints"
                  - "ec2:DescribeVpcs"
                Resource: "*"
              - Effect: Allow
                Action:
                  - "sagemaker:AddTags"
                Resource: "*"
              - Effect: Allow
                Action:
                  - "iam:ListRoles"
                Resource: "*"
      ManagedPolicyName: SMStudioReadOnlyPolicy
      Roles: 
        - SMStudioAdminRole
  SMStudioSupportServicesPolicy:                                                                                                                                                                                                                                                                     
    DependsOn: SMStudioAdminRole
    Type: AWS::IAM::ManagedPolicy
    Properties: 
      PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "s3:PutObject"
                  - "s3:GetObject"
                  - "s3:AbortMultipartUpload"
                  - "s3:DeleteObject"
                  - "s3:CreateBucket"
                  - "s3:ListBucket"
                  - "s3:PutBucketCORS"
                  - "s3:ListAllMyBuckets"
                  - "s3:GetBucketCORS"
                  - "s3:GetBucketLocation"
                Resource: "*"
              - Effect: Allow
                Action:
                  - "kms:DescribeKey"
                  - "kms:ListAliases"
                Resource: "*"
              - Effect: Allow
                Action:
                  - "ecr:Set*"
                  - "ecr:CompleteLayerUpload"
                  - "ecr:Batch*"
                  - "ecr:Upload*"
                  - "ecr:InitiateLayerUpload"
                  - "ecr:Put*"
                  - "ecr:Describe*"
                  - "ecr:CreateRepository"
                  - "ecr:Get*"
                  - "ecr:StartImageScan"
                Resource: "*"
              - Effect: Allow
                Action:
                  - "elasticfilesystem:DescribeFileSystems"
                  - "servicecatalog:ListAcceptedPortfolioShares"
                  - "cloudshell:*"
                  - "cloudwatch:Put*"
                  - "cloudwatch:Get*"
                  - "cloudwatch:List*"
                  - "cloudwatch:DescribeAlarms"
                  - "logs:Put*"
                  - "logs:Get*"
                  - "logs:List*"
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:ListLogDeliveries"
                  - "logs:Describe*"
                  - "logs:CreateLogDelivery"
                  - "logs:PutResourcePolicy"
                  - "logs:UpdateLogDelivery"
                Resource: "*"
      ManagedPolicyName: SMStudioSupportServicesPolicy
      Roles: 
        - SMStudioAdminRole
  SMStudioUserPolicy:                                                                                                                                                                                                                                                                     
    Type: AWS::IAM::ManagedPolicy
    Properties: 
      PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "sagemaker:CreatePresignedDomainUrl"
                Resource: "*"
                Condition:
                  StringEquals:
                    sagemaker:ResourceTag/studiouserid: ${aws:username}
      ManagedPolicyName: SMStudioUserPolicy
  SMStudioUser1: 
    DependsOn: [SMStudioUserPolicy, SMStudioReadOnlyPolicy, SMStudioSupportServicesPolicy, SMStudioDevPolicy]
    Type: AWS::IAM::User
    Properties: 
      LoginProfile: 
        Password: Workshopuser#123
        PasswordResetRequired: false
      ManagedPolicyArns: 
        - !Ref SMStudioUserPolicy
        - !Ref SMStudioReadOnlyPolicy
        - !Ref SMStudioSupportServicesPolicy
        - !Ref SMStudioDevPolicy
      UserName: smstudiouser1
  SMStudioUser2:
    DependsOn: [SMStudioUserPolicy, SMStudioReadOnlyPolicy, SMStudioSupportServicesPolicy, SMStudioDevPolicy]        
    Type: AWS::IAM::User
    Properties: 
      LoginProfile: 
        Password: Workshopuser#123
        PasswordResetRequired: false
      ManagedPolicyArns: 
        - !Ref SMStudioUserPolicy
        - !Ref SMStudioReadOnlyPolicy
        - !Ref SMStudioSupportServicesPolicy
        - !Ref SMStudioDevPolicy
      UserName: smstudiouser2
Outputs:
  SMStudioAdminRoleArn:
    Description: Admin Role Arn
    Value:  !GetAtt SMStudioAdminRole.Arn